### ISSUE TITLE
og image showing up when sharing link to www.igniterealtime.org on FB & Linkedin

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/IgniteRealtime-Website#166]
Hello,

When sharing link https://www.igniterealtime.org on linkedIN or Facebook, og image is not defined. It takes the first image on page for linkedIN and no image on FB. This could be fixed by adding proper meta og image tags.
On linkedIN 
![screenshot9](https://user-images.githubusercontent.com/29485972/89231091-ea657980-d5e4-11ea-89d3-f37ef0979aa1.png)
On facebook no og image
![screenshot11](https://user-images.githubusercontent.com/29485972/89231128-fbae8600-d5e4-11ea-8cbe-00efb5e1bb45.png)

I did not check out with twitter but probably similar issue
It will look more pro when sharing links at ignite on social networks. Not a big issue at all but could give a better view of targeted site content, it always ease propagation and interests

Thanks in advance for taking the point

**Comment by Neustradamus** [comment]
@ClaudeStabile: The problem is always here?

**Comment by guusdk** [comment]
@ClaudeStabile A few hours ago, the website started to include OG headers. Can you check if things look better now please?

**Comment by ClaudeStabile** [comment]
![screenshot3](https://user-images.githubusercontent.com/29485972/148384393-265b2027-5290-45a0-9355-12274ca32ce0.png)
@guusdk @Neustradamus 

Thanks it looks better now on social networks

My very best wishes for 2022 to both of you

++
