### ISSUE TITLE
Openfire 3.60 Nightly build download page no .deb packages as usual and as mentioned only .rpm 

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/IgniteRealtime-Website#168]
I was expecting to download a fresh .deb OF nightly build package. But when i go on page only rpm packages are available. I need .deb packages to build up a docker image with latest OF so i could experiment and test

Any option to go back to .deb for nightly build packages ?

This would greatly help for testing purposes mainly

Thanks in advance

![screenshot2](https://user-images.githubusercontent.com/29485972/90547572-02fc9480-e18c-11ea-9037-16898ecffa97.png)

**Comment by akrherz** [comment]
Thanks for pointing this out.  We recently updated the web host to a newer Linux and failed to update the bamboo debian build host to allow uploading its daily build artifact to the website.  This should be corrected now going forward.  With regards to docker, have you see [this repo](https://github.com/igniterealtime/Docker).

**Comment by ClaudeStabile** [comment]
Cool :)  Thx for deb package !
For docker, i build my own separated docks images for many good reasons. Anyway your approach is also very interesting
